export const FETCH_GENETIC_RESPONSE_START = "FETCH_GENETIC_RESPONSE_START";
export const FETCH_GENETIC_RESPONSE_ACK = "FETCH_GENETIC_RESPONSE_ACK";
export const FETCH_GENETIC_RESPONSE_ERROR = "FETCH_GENETIC_RESPONSE_ERROR";
