export const FETCH_GENETIC_RESPONSE_START = "FETCH_GENETIC_RESPONSE_START";
export const FETCH_GENETIC_RESPONSE_ACK = "FETCH_GENETIC_RESPONSE_ACK";
export const FETCH_GENETIC_RESPONSE_ERROR = "FETCH_GENETIC_RESPONSE_ERROR";

export const MODIFY_A_VALUE = "MODIFY_A_VALUE";
export const MODIFY_B_VALUE = "MODIFY_B_VALUE";
export const RESET_ALL_VALUES = "RESET_ALL_VALUES";